version: "0.2"
# Suggestions can sometimes take longer on CI machines,
# leading to inconsistent results.
suggestionsTimeout: 5000 # ms
allowCompoundWords: true
dictionaries:
  - bash
  - companies
  - css
  - dotnet
  - docker
  - en_us
  - filetypes
  - fonts
  - html
  - makefile
  - misc
  - node
  - npm
  - people-names
  - powershell
  - python
  - softwareTerms
  - typescript
words:
  # Tooling Usernames
  - Knister
  - vivaxy
  - tamasfe
  # Code Terms
  - azdo
  - all-contributorsrc
  - hadolint
  - pscore
  - ZDOTDIR
