version: "0.2"
# Suggestions can sometimes take longer on CI machines,
# leading to inconsistent results.
suggestionsTimeout: 5000 # ms
allowCompoundWords: true
dictionaries:
  - en_us
  - dotnet
  - makefile
  - powershell
  - python
  - npm
words:
  # Tooling Usernames
  - natescherer
  - scherer
  - joshbolduc
  - Knister
  - vivaxy
  # Code Terms
  - contributorsrc
  - azdo
  - ZDOTDIR
