name: "[Test] PR Validation"

on:
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: read-all

env:
  MISE_ENV: ci

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@v3
        with:
          experimental: true
      - id: changed-files
        uses: tj-actions/changed-files@v46.0.5
      - name: Run Pre-Commit Tests
        run: |
          mise x -- pre-commit run -c .config/.pre-commit-config.yaml --files ${{ steps.changed-files.outputs.all_changed_files }}
      - name: Example Test
        run: |-
          FILE=README.md
          if [ -f "$FILE" ]; then
            echo "$FILE exists."
            echo "Also you should probably put one or more real checks relevant to your project here."
          else
            echo "$FILE missing!"
            exit 1
          fi
