name: "Update: Copier Parent Template"

on:
  schedule:
    - cron: 0 17 * * 1 # Every Monday at 5pm UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: Get New Template Version
        id: get_ver
        shell: pwsh
        run: |
          $Output = copier update --skip-answered --pretend --trust 2>&1
          $NewVersion = $Output[0].ToString().Split(" ")[-1]
          echo "NEW_VERSION=$NewVersion" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
      - name: Run Copier Update
        run: |
          copier update --skip-answered --trust
          git add .
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.REPO_MAINTENANCE_PAT }}
          commit-message: "feat: copier update to parent template v${{ steps.get_ver.outputs.NEW_VERSION }}"
          branch: "copier-template-update-v${{ steps.get_ver.outputs.NEW_VERSION }}"
          delete-branch: true
          title: "feat: copier update to parent template v${{ steps.get_ver.outputs.NEW_VERSION }}"
          body: |
            Copier has applied updates from parent template v${{ steps.get_ver.outputs.NEW_VERSION }}.

            Review and push any needed changes to the `copier-template-update-v${{ steps.get_ver.outputs.NEW_VERSION }}` branch.
  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
